Imports System.ComponentModel

Imports CommunityToolkit.Mvvm.ComponentModel

Partial Public Class ProcessorConfiguration : Inherits ObservableObject : Implements ISaveable

    Public Property Version As Single = 0.1 Implements ISaveable.Version
    Public Property Name As String = "Configuration" Implements ISaveable.Name

    Public Enum ToolMode
        Cut
        Draw
        Deboss
        Engrave

    End Enum

    Public Property SelectedToolMode As ToolMode = ToolMode.Draw

    'Shared Variables
    Public Property Tolerance As Double = 0.01
    Public Property AutoUnionText As Boolean = True
    Public Property WorkSpeed As Double = 40
    Public Property TravelSpeed As Double = 60
    Public Property ZSpeed As Double = 10
    Public Property WorkZ As Double = 0
    Public Property TravelZ As Double = 5
    Public Property SafeZ As Double = 10

    Public Property WorkAreaWidth As Double = 200
    Public Property WorkAreaHeight As Double = 200


    Public Property CuttingConfig As New CuttingConfiguration
    Public Property DrawingConfig As New DrawingConfiguration
    Public Property ExportConfig As New ExportConfiguration




    ''' Currently only supported by GCodePlot
    Public Property ExtractOneColour As Boolean = False
    Public Property ExtractionColor As String = ""
    Public Property InsideOutCuttingOrder As Boolean = False
    Public Property OptimisationTimeout As Integer = 60
    Public ReadOnly Property Area As String
        Get
            Return $"""0,0,{WorkAreaWidth},{WorkAreaHeight}"""
        End Get
    End Property

End Class

Partial Public Class CuttingConfiguration : Inherits ObservableObject

    Public Property ToolDiameter As Double = 0.9
    Public Property Overcut As Double = 0

    Public ReadOnly Property ToolRadius
        Get
            Return ToolDiameter / 2
        End Get
    End Property

End Class

Partial Public Class DrawingConfiguration : Inherits ObservableObject

    Public Property MinStrokeWidth As Double = 1
    Public Property CrossHatch As Boolean = True
    Public Property ShadingAngle As Double = 45
    Public Property KeepOutlines As Boolean = True


    ''' Currently only supported by GCodePlot
    Public Property MaxStrokeWidth As Double = 1
    Public Property DrawingDirection As Integer? = Nothing
    Public Property ShadingThreshold As Double = 1

End Class

Partial Public Class GCodeConfiguration : Inherits ObservableObject

    Private Property InitialGCode As New List(Of GCode) From {
        GCode.CommentLine("Generated by PolyCut 0.1"),
        GCode.Parse("G0 E0"),
        GCode.Parse("G21"),
        GCode.Parse("G28")}

    Private Property EndGCode As New List(Of GCode) From {
        GCode.CommentLine($" OrcaSlicer PolyCut 0.1 on_"),
        GCode.CommentLine($" estimated printing time = 0"),
        GCode.CommentLine($" filament used [mm] = 0")}


    Public Sub SetInitialGCode(gcodes As List(Of GCode))
        InitialGCode.Clear()
        InitialGCode.AddRange(gcodes)
    End Sub

    Public Function GetInitialGCode() As List(Of GCode)
        Return InitialGCode
    End Function

    Public Sub SetEndGCode(gcodes As List(Of GCode))
        EndGCode.Clear()
        EndGCode.AddRange(gcodes)
    End Sub
    Public Function GetEndGCode()
        Return EndGCode
    End Function

End Class



Partial Public Class ExportConfiguration : Inherits ObservableObject

    Public Enum ExporterType
        Network
        File
    End Enum

    Public Property Type As ExporterType = ExporterType.Network
    Public Property FileDestination As String = Nothing
    Public Property DestinationIP As String = "klipper.local"
    Public Property DestinationPort As Integer = 7125
    Public Property AutoPrint As Boolean = True


End Class

