<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PolyCut.Localisation</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>PolyCut.Localisation</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.9.0" />
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>

</Project>
